### ISSUE TITLE
UI aborting transfers

### ISSUE THREAD

**Issue by ChronicSmoke** [ChainSafe/chainbridge-ui#103]
## Expected Behavior

The UI submits the transaction
## Current Behavior

https://user-images.githubusercontent.com/84600919/130494981-3bcb50bf-22b4-4a32-89c6-de3bc4c23858.mp4

![image](https://user-images.githubusercontent.com/84600919/130494846-f3fffb24-6fed-4674-bb1b-15b38064330c.png)

**Comment by P1sar** [comment]
closing duplicate of https://github.com/ChainSafe/ChainBridge/issues/700
