### ISSUE TITLE
UI element that displays number of relayers online

### ISSUE THREAD

**Issue by ChronicSmoke** [ChainSafe/chainbridge-ui#107]
## Story
As a maintainer of a bridge relayer
I want a UI element that displays the number of relayers online and disables the rest of the bridge UI if the threshold of signers isn't met.
So that I can avoid having to enter into recovering funds if somebody used the bridge while the relayers were done

## Background
I am running a bridge from our network to the Ethereum chain.  I don't like that there isn't any error checking that the bridge is capable of making the transfer (i.e. enough relays are online) before allowing users to attempt to send their funds across. This would be a nice feature to avoid having to enter into recovering lost funds.

## Implementation details

A small UI element that displays a red or green circle with a x / total relayers online next to it.  the circle is green if enough relayers are online and the rest of the UI is visible and usable.  If there are not enough relayers online the circle is red and the UI becomes greyed out (not accepting input or interacting with the send button) and displays a message to the effect of: "sorry, the bridge is offline please check back later."

**Comment by P1sar** [comment]
Hey! Thanks for pointing us to such feature. But currently it can't be done in any reasonable way since there is not any way how we can check relayer availability. Although we are gonna hold this in mind so maybe we will come with solution one day
