### ISSUE TITLE
How can we limit the transfer amount on the Transfer Page.jsx

### ISSUE THREAD

**Issue by tomrisirtom** [ChainSafe/chainbridge-ui#113]
How can we limit the transfer amount on the Transfer Page.jsx page. 
For example, the user can transfer a maximum of 5000 units. If user want to transfer more than that, he should be warned about the limit.

**Comment by wainola** [comment]
Currently if you try to transfer an amount that exceeds the maximum present in the account, when you try to make the transfer an error message appears indicating that you do not have enough funds to be transferred, so the UI simply will not allow such a transfer

**Comment by tomrisirtom** [comment]
Regardless of the amount in the account, for example, only a maximum of 50 ERC20 might be transferred. 
Even if you have 70 in your account, it should not allow you to send more than 50.
How can we do it?

**Comment by P1sar** [comment]
There is not such functionality added to the UI, and we are not planning to add it in future. So you can implement it and make a PR or fork entire repo for your purposes
