### ISSUE TITLE
Add select for home and destination network

### ISSUE THREAD

**Issue by enemycnt** [ChainSafe/chainbridge-ui#139]
We should have two select dropdowns to filter source and destination network. 
The list of the network should be requested from the API
**NOTE** Filtering should happen on the server side. Front end need to knows about possible options only for UX purposes. When user selects some filter, new request should went to server

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/139?planning-poker) with ZenHub @enemycnt @wainola
