### ISSUE TITLE
Add filter for deposit hash

### ISSUE THREAD

**Issue by enemycnt** [ChainSafe/chainbridge-ui#141]
Connect deposit hash search form markup to the API
<img width="276" alt="Screenshot 2021-10-12 at 15 17 57" src="https://user-images.githubusercontent.com/320313/136954615-01424f8b-acdf-4ed1-a70f-13b817b616ae.png">

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/141?planning-poker) with ZenHub @enemycnt @wainola
