### ISSUE TITLE
Add filter for "my" and "all" transfers

### ISSUE THREAD

**Issue by enemycnt** [ChainSafe/chainbridge-ui#142]
Add a button to filter "my" or "all" transfers.
Show all transfers by default
If the user clicks on "my" we should connect user's meatamask and use his wallet address to filter the transactions.
If the user has already connected his metamask, show the user's transfers. Otherwise, show all transfers

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/142?planning-poker) with ZenHub @enemycnt @wainola
