### ISSUE TITLE
Setup, run and test UI with substrate network

### ISSUE THREAD

**Issue by wainola** [ChainSafe/chainbridge-ui#180]
## Background

We need setup and run local substrate network to test transfer between EVM <> Substrate with the UI

## Implementation details

Manage to run the UI connected to substrate network

## Testing details

- Connect UI to substrate wallet
- Check that UI doesn't have any errors on connection
- Create example runtime config with substrate network

## Acceptance criteria

[] Substrate have been run locally and UI connected to it

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/180?planning-poker) with ZenHub @enemycnt @wainola
