### ISSUE TITLE
Refactor Substrate context provider

### ISSUE THREAD

**Issue by wainola** [ChainSafe/chainbridge-ui#181]
## Background

After proper local setup, we can test and refactor context provider for substrate network

## Implementation details

- Extracting functions and hooks to separate files
- Derive utility functions

## Testing details

- Transfer from EVM to Substrate should work as expected
- Transfer from Substrate to EVM should work as expected

## Acceptance criteria

- Context module reduced in order to have smaller amount of side effects
- Single responsibility pattern used over Substrate related modules

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/181?planning-poker) with ZenHub @enemycnt @wainola
