### ISSUE TITLE
Refactoring of providers

### ISSUE THREAD

**Issue by enemycnt** [ChainSafe/chainbridge-ui#183]
Change logic and structure of providers

## Implementation details

- Reduce the complexity of NetworkManagerContext.jsx
- Create the architecture of providers with the possibility to extend for new network support
- Remove unnecessary dependency injections between the providers, make them more isolated

## Testing details
- Transfers from EVM to EVM should work as expected.

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/183?planning-poker) with ZenHub @wainola @enemycnt
