### ISSUE TITLE
Transfer page view refactoring

### ISSUE THREAD

**Issue by enemycnt** [ChainSafe/chainbridge-ui#185]
Refactor TransferPage and Modal
## Implementation details

- Refactor transfer page, change formik to react-hook-form
- Refactor modals
- Check the possibility to implement latest MaterialUI

## Acceptance Criteria

[] Business logic should be separated from page rendering
[] Come up with the answer about does it possible to add MaterialUI in to UI, and how long could it take

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/185?planning-poker) with ZenHub @enemycnt @wainola
