### ISSUE TITLE
Celo to Besu UI confirmation message is reverted 

### ISSUE THREAD

**Issue by taha-be** [ChainSafe/chainbridge-ui#187]
The transfer from Celo to Besu network went thru without issues, however, the final message says “from Ethereum – Besu to Celo – Alfajores”, shouldn’t it be “from Celo – Alfajores to Ethereum – Besu”

## Expected Behavior
 it be “from Celo – Alfajores to Ethereum – Besu”

## Current Behavior
The confirmation message is currently reverted. It says "from Ethereum – Besu to Celo – Alfajores”. The correct behaviour should be the other way around "from Celo – Alfajores to Ethereum – Besu”.

![unnamed](https://user-images.githubusercontent.com/60484508/144223715-a326f322-53d4-47e4-86c4-0b6787333e6a.png)

## Steps to Reproduce (for bugs)
1.Use the Celo alfajores <> Besu bridge. 
2. Swap cUSD to TWCBDC.

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/187?planning-poker) with ZenHub @enemycnt @wainola
