### ISSUE TITLE
UI SDK Business requirements 

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-ui#188]
Before we can start working on the SDK for ChainBridge UI we need to define technical and business requirements.
## Implementation details

First we should define list of business requirements for SDK to set expectation from business. 
## Acceptance Criteria

1. Business requirements for SDK written

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/188?planning-poker) with ZenHub @wainola @enemycnt @taha-be

**Comment by taha-be** [comment]
I'm gathering my notes on this document:
https://docs.google.com/document/d/1mpxMPtQakpNCifNWjVoMkEmgaLjbBNDRycbrbp8RgB4/edit?usp=sharing
