### ISSUE TITLE
Replace onobard.js with own connection logic

### ISSUE THREAD

**Issue by wainola** [ChainSafe/chainbridge-ui#221]
## Implementation details

- Prepare reducer as a single source of truth for balances and accounts.
- Create our own connection logic and replace it for onboard.js (ie: removing some functions calls from onboard.js api, like walletSelect and walletCheck) using web3-react dependency.
- create the modal (ie: using Dialog component from MUI) to replace onboard.js UX.
- remove NetworkConnectionModal component

## Testing details

- manual tests

## Acceptance Criteria

- curent UI should behave the same as right now, but wihtout onboard.js connection logic
- connect to wallet, transfer tokens

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/221?planning-poker) with ZenHub @enemycnt @wainola
