### ISSUE TITLE
Fix transfer using gnosis vault and wallet connect

### ISSUE THREAD

**Issue by wainola** [ChainSafe/chainbridge-ui#226]
After connecting the UI with wallet connect to the gnosis vault, if we try to transfer some tokens, there is only one approval and the UI get stuck waiting of the second one. Nothing happens afterwards.

## Testing details

- Manual testing

## Acceptance Criteria

- transfers tokens authorizing those with Gnosis Vault

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/226?planning-poker) with ZenHub @enemycnt @wainola
