### ISSUE TITLE
Replace transfer logic with chainbridge SDK

### ISSUE THREAD

**Issue by wainola** [ChainSafe/chainbridge-ui#234]
## Implementation details

- replace transfer logic with the usage of the new `chainbridge-sdk` in our current UI
- refactor/adapt/change the code related to transfer tokens: instead of using `homeBridge.deposit` change for the new transfer method.
- Adjust also the state and context variables that are going to be affected by this change

## Testing details

- Manual transfer of tokens

## Acceptance Criteria

- UI should work the same ways as it was.

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-ui/234?planning-poker) with ZenHub @enemycnt @wainola
