### ISSUE TITLE
Unable reset TransactionStatus when click "Start new transfer"

### ISSUE THREAD

**Issue by ss22219** [ChainSafe/chainbridge-ui#244]
https://github.com/ChainSafe/chainbridge-ui/blob/671dc6062d32321553ad7b852b520940dc09faf3/packages/core/src/reducers/web3Reducers/networkManagerReducer.ts#L48

**Comment by enemycnt** [comment]
This code is stale. Right now we are working on extracting all the bridge-related logic to the separate SDK. It hasn't been officially released, but it's going to be published in the nearest future.
