### ISSUE TITLE
Example UI doesn't detect proposal vote event

### ISSUE THREAD

**Issue by xiaohanzhu** [ChainSafe/chainbridge-ui#247]
configured the UI for Rinkby and Moonbase Alpha.  The relayer is based on the main branch in chainbridge-core-example.  The proposal has been voted and executed on the destination chain, but the UI did not detect the event for the proposal vote.
![image](https://user-images.githubusercontent.com/9540395/171333517-03a8a56f-7b34-4e93-86ee-cb08da8bf9fd.png)

**Comment by wainola** [comment]
Hi, we are currently working on this issue that is present in our SDK, that serves us as the base implementation for all the busines logic related to transfer. Once we fix this, we are going to update the UI to show the events properly using our current SDK.
