### ISSUE TITLE
Can't build UI due to missing dependency

### ISSUE THREAD

**Issue by ArseniiPetrovich** [ChainSafe/chainbridge-ui#33]
I'm trying to build the UI. I've provided access token with "package:read" permissions, started `yarn build` and seeing the following error:
2:57:40 PM: error An unexpected error occurred: "https://npm.pkg.github.com/download/@imploy/common-components/1.0.24/bc910d5393b6486beb75326b0761fa2fff80dbaf8b43f6f018156c1ba4fb5f38: Request failed \"404 Not Found\"".

This is what I see when using my creds to access this site manually:
![image](https://user-images.githubusercontent.com/23522179/99669521-3cd98180-2a80-11eb-9332-40e70ce56d12.png)

**Comment by FSM1** [comment]
I have updated the dependencies to use a public version of the packages in question.
