### ISSUE TITLE
Cannot enter amout without selecting token

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-ui#38]
The amount field is locked before selecting a token. This is an annoying UX, we should either unlock it or add some signal the user should select a token (or reverse the order of these two components?)

![Screenshot_2020-11-23_10-32-47](https://user-images.githubusercontent.com/14164624/99981330-43654300-2d77-11eb-9d31-ab8f25aaa031.png)

**Comment by FSM1** [comment]
This is what the Near bridge looks like:
![image](https://user-images.githubusercontent.com/12774278/118132824-6a383400-b400-11eb-8c91-12eae4e9e16c.png)
![image](https://user-images.githubusercontent.com/12774278/118132852-6f957e80-b400-11eb-936f-63ee8af0b88b.png)

**Comment by ansermino** [comment]
Seems we should swap these components then. The first interaction should be with the component in the left - since we read left to right and following what Near has.
