### ISSUE TITLE
Wrapping progress improvements

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-ui#43]
Currently the window has not edge and just blends into the background. There is also no way to tell if it's processing or frozen.

![Screenshot_2020-11-23_15-40-58](https://user-images.githubusercontent.com/14164624/100013199-6f49ee00-2da2-11eb-9ad2-6f4c571c0568.png)

**Comment by FSM1** [comment]
Progress bar has been added to the wrapper here https://github.com/ChainSafe/chainbridge-ui/commit/65bec38027294714f341417130b1089eaf63d4a7
