### ISSUE TITLE
Chainbridge Explorer Event Indexer

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/chainbridge-ui#69]
[Notion](https://www.notion.so/chainsafe/Explorer-Project-Plan-2d6d9c5bb34f4b1698e447efddceb838#7c23aecd074a40848636986e56d63d8c)
An indexer should be built that exposes a REST/GraphQL endpoint

- Substrate does not support event querying and as such getting this data quickly enough for good UX will require an indexer.
- Since the current client-side indexing architecture is clearly constrained by RPC, it makes sense to also handle indexing of EVM events in the same database.

![image](https://user-images.githubusercontent.com/12774278/116161754-aa0ad600-a6f4-11eb-9e5d-a0a3f0c89786.png)

- An indexer will require:
    - A full network bridge config (RPC, contract addresses
    - Database config
- The indexers will handle storing the following events:
    - Add Deposit Record
    - Add Proposal Vote
    - Add Proposal Event

The events above should be used to build up the following object describing each transfer:
```
type DepositRecord = {
  fromAddress?: string;
  fromChainId?: number;
  fromNetworkName?: string;
  toAddress?: string;
  toChainId?: number;
  toNetworkName?: string;
  tokenAddress?: string;
  amount?: BigNumber;
  timestamp?: number;
  depositTransactionHash?: string;
  depositBlockNumber?: number;
  proposalEvents: Array<{
    proposalStatus: ProposalStatus;
    dataHash?: string;
    proposalEventTransactionHash?: string;
    proposalEventBlockNumber: number;
    timestamp: number;
  }>;
  votes: Array<{
    voteStatus: boolean;
    voteTransactionHash?: string;
    voteBlockNumber: number;
    timestamp: number;
    dataHash: string;
  }>;
};
```

Following deployment and testing of the indexing & querying API, all the event listener code in ExplorerContext.tsx should be removed and replaced with API queries.

The current code in [ExplorerContext](https://github.com/ChainSafe/chainbridge-ui/blob/main/src/Contexts/ExplorerContext.tsx) should be used as a base for the EVM chain indexer.

**Comment by P1sar** [comment]
This issue will be moved to the new repo for the Indexer of Explorer UI
