### ISSUE TITLE
UI not finalizing "In Transit" Events - not progressing to tx completed stage

### ISSUE THREAD

**Issue by chris-shyft** [ChainSafe/chainbridge-ui#84]
<img width="401" alt="Screen Shot 2021-08-09 at 2 57 33 PM" src="https://user-images.githubusercontent.com/34154131/128759289-f4b07bc1-981c-49b3-9c6c-cb731e84d0c4.png">

stalls here indefinitely, on-chain events/progression does occur, so tx does go through it's just not reflected on the UI

**Comment by P1sar** [comment]
@enemycnt  so problem was with not turned on Realyers? We can close it?

**Comment by enemycnt** [comment]
Closed in favor of #93
