### ISSUE TITLE
Write Guide for setting up metamask networks manually

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-ui#98]
Currntly to use UI with Celo network we need to setup it manually. It is not hard process but we need to provide guiding documentation for users.
## Implementation details

Try to use UI with along with CELO ALfajores <> RInkebay deployment and write the guide about how it should be done.
Guide should include sreen shots. And should be written in abstract manner but using Alfajores network as example. 
@Jon is responsible for writing the docs, @taha-be should help and test @enemycnt will help with process

## Testing details

Non tech user is able to setup metamask and send transactions

## Acceptance Criteria

Non tech user is able to setup metamask and send transactions

**Comment by waymobetta** [comment]
[MetaMask network/token configuration guide](https://hackmd.io/@tahabe/Hyjb4c9eK/edit) exists on @taha-be hackmd account

We can either add on top of this or keep them as 2 separate guides: 
- one for configuring a new network/token on MetaMask
- the other for actual chainbridge UI usage

MetaMask also already provides a guide on [how to configure a custom network](https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-custom-Network-RPC), so we probably also want to avoid duplicate work unless this is specific to a certain integration

**Comment by waymobetta** [comment]
Guide added to gitbook and [chainbridge-docs](https://github.com/ChainSafe/chainbridge-docs/blob/develop/docs/guides/metamask-network-setup-guide.md)
